.PHONY: build test clean

build: test
	GOOS=linux GOARCH=amd64 go build -buildvcs=false -o=cmd/server ./cmd/server/...
	GOOS=linux GOARCH=amd64 go build -buildvcs=false -o=cmd/agent ./cmd/agent/...

test: clean
	GOOS=linux GOARCH=amd64 go build -buildvcs=false -o=cmd/staticlint ./cmd/staticlint/...
	go vet -vettool=cmd/staticlint/staticlint ./...
	go mod tidy
	go mod vendor
	go clean -testcache
	go test ./...
