.PHONY: build test clean

build: 
	go clean -testcache
	GOOS=linux GOARCH=amd64 go build -buildvcs=false -o=cmd/server ./cmd/server/...
	GOOS=linux GOARCH=amd64 go build -buildvcs=false -ldflags "-X main.buildVersion=v1.0.1 -X 'main.buildDate=$(date +'%Y-%m-%d')' -X 'main.buildCommit=$(git rev-parse HEAD)'" -o=cmd/agent ./cmd/agent/...

test: build
	GOOS=linux GOARCH=amd64 go build -buildvcs=false -o=cmd/staticlint ./cmd/staticlint/...
	cmd/staticlint/staticlint ./...
	go mod tidy
	go mod vendor
	go test ./...
